name: Build grassh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install yq
        run: curl.exe -o C:\Windows\System32\yq.exe -L https://github.com/mikefarah/yq/releases/latest/download/yq_windows_amd64.exe
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - run: flutter build windows --build-number=${{ github.run_number }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassh-windows
          path: build\windows\x64\runner\Release

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux --build-number=${{ github.run_number }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassh-linux
          path: build/linux/x64/release/bundle/
      

  macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - run: flutter build macos --build-number=${{ github.run_number }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassh-macos
          path: build/macos/Build/Products/Release/
